name: Odoo Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux, prod]
    steps:
      - name: Deploy main branch
        run: |
          cd /opt/odoo/premium_jobs
          git fetch origin
          git reset --hard origin/main
          sudo systemctl restart odoo
